language: android
jdk: oraclejdk8

android:
  components:
    - tools # repository-11
    - tools # upgrade tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'
script:
  - chmod 777 gradlew
  - ./gradlew clean assembleDebug
after_success:
  - bash <(curl -s https://codecov.io/bash)